[package]
name = "lattice"
version = "0.0.0"
authors = ["hxyulin <hxyulin@proton.me>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/hxyulin/lattice"
build = "build.rs"

[features]
profiling = []
nnue-eval = []

[dependencies]
nonmax = "0.5"

[dev-dependencies]
criterion = { version = "0.5", default-features = false }

[[bin]]
name = "lattice"
path = "src/main.rs"

[[bench]]
name = "search"
harness = false

[lints.rust]
missing_docs = "warn"

[lints.clippy]
all = "warn"

[profile.dev.package.lattice]
opt-level = 2

[profile.profiling]
inherits = "release"
debug = true

[[bench]]
name = "hot_paths"
harness = false
