//! Safe generation of reviewable tuned-weight artifacts.

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use super::features::PARAMETER_COUNT;

pub(crate) fn write_artifacts(
    directory: &Path,
    parameters: &[i32; PARAMETER_COUNT],
    report: &str,
) -> io::Result<()> {
    fs::create_dir_all(directory)?;
    let weights_path = directory.join("tuned_weights.rs");
    let report_path = directory.join("training-report.txt");
    for path in [&weights_path, &report_path] {
        if path.exists() {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                format!("refusing to overwrite {}", path.display()),
            ));
        }
    }
    fs::write(weights_path, render_weights(parameters))?;
    fs::write(report_path, report)?;
    Ok(())
}

fn render_weights(parameters: &[i32; PARAMETER_COUNT]) -> String {
    let mut out = String::from(concat!(
        "//! Generated by `lattice tune`; replace `src/eval_weights.rs` explicitly after review.\n\n",
        "use super::{\n",
        "    DOUBLED_EG, DOUBLED_MG, EG_TABLE, EvalWeights, ISOLATED_EG, ISOLATED_MG, MG_TABLE, MOBILITY_EG,\n",
        "    MOBILITY_MG, PASSED_EG, PASSED_MG, ROOK_OPEN_EG, ROOK_OPEN_MG, ROOK_SEMI_EG, ROOK_SEMI_MG,\n",
        "    TEMPO,\n",
        "};\n\n",
        "const _: () = {\n",
        "    let _ = (MG_TABLE, EG_TABLE, MOBILITY_MG, MOBILITY_EG);\n",
        "    let _ = (ROOK_OPEN_MG, ROOK_OPEN_EG, ROOK_SEMI_MG, ROOK_SEMI_EG);\n",
        "    let _ = (\n",
        "        PASSED_MG,\n",
        "        PASSED_EG,\n",
        "        ISOLATED_MG,\n",
        "        ISOLATED_EG,\n",
        "        DOUBLED_MG,\n",
        "        DOUBLED_EG,\n",
        "        TEMPO,\n",
        "    );\n",
        "};\n\n",
        "#[rustfmt::skip]\n",
        "pub(crate) const WEIGHTS: EvalWeights = EvalWeights {\n",
    ));
    render_table(&mut out, "mg_table", &parameters[0..384]);
    render_table(&mut out, "eg_table", &parameters[384..768]);
    let _ = writeln!(
        out,
        "    mobility_mg: [0, {}, {}, {}, {}, 0],",
        parameters[768], parameters[769], parameters[770], parameters[771]
    );
    let _ = writeln!(
        out,
        "    mobility_eg: [0, {}, {}, {}, {}, 0],",
        parameters[772], parameters[773], parameters[774], parameters[775]
    );
    for (name, index) in [
        ("rook_open_mg", 776),
        ("rook_open_eg", 777),
        ("rook_semi_mg", 778),
        ("rook_semi_eg", 779),
    ] {
        let _ = writeln!(out, "    {name}: {},", parameters[index]);
    }
    render_array(&mut out, "passed_mg", &parameters[780..787], 4);
    render_array(&mut out, "passed_eg", &parameters[787..794], 4);
    for (name, index) in [
        ("isolated_mg", 794),
        ("isolated_eg", 795),
        ("doubled_mg", 796),
        ("doubled_eg", 797),
        ("tempo", 798),
    ] {
        let _ = writeln!(out, "    {name}: {},", parameters[index]);
    }
    out.push_str("};\n");
    out
}

fn render_table(out: &mut String, name: &str, values: &[i32]) {
    let _ = writeln!(out, "    {name}: [");
    for piece in values.chunks_exact(64) {
        out.push_str("        [\n");
        for row in piece.chunks_exact(8) {
            out.push_str("            ");
            for value in row {
                let _ = write!(out, "{value:>5},");
            }
            out.push('\n');
        }
        out.push_str("        ],\n");
    }
    out.push_str("    ],\n");
}

fn render_array(out: &mut String, name: &str, values: &[i32], width: usize) {
    let _ = write!(out, "    {name}: [");
    for value in values {
        let _ = write!(out, "{value:>width$},");
    }
    out.push_str("],\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_module_contains_every_weight_family() {
        let text = render_weights(&[0; PARAMETER_COUNT]);
        assert!(text.contains("mg_table:"));
        assert!(text.contains("eg_table:"));
        assert!(text.contains("mobility_mg:"));
        assert!(text.contains("passed_eg:"));
        assert!(text.contains("tempo:"));
        assert!(text.contains("\n    DOUBLED_EG, DOUBLED_MG, EG_TABLE, EvalWeights"));
        assert!(text.contains("\n        PASSED_MG,"));
    }
}
